//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTeguhJaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class barang
    {
        public int id_gudang { get; set; }
        public string nama { get; set; }
        public string jenis { get; set; }
        public string suplier { get; set; }
        public int modal { get; set; }
        public int harga_atas { get; set; }
        public int harga_bawah { get; set; }
        public int jumlah { get; set; }
        public int sisa { get; set; }
        public System.DateTime tangal_masuk { get; set; }
    }
}
