//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTeguhJaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class barang_terjual
    {
        public int id_terjual { get; set; }
        public int id_barangtoko { get; set; }
        public int jual_idpelanggan { get; set; }
        public int jual_hargaakhir { get; set; }
        public int jual_jumlah { get; set; }
        public System.DateTime tanggal { get; set; }
        public int id_transaksi { get; set; }
    }
}
