//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTeguhJaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class grosirEntities : DbContext
    {
        public grosirEntities()
            : base("name=grosirEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<barang> barangs { get; set; }
        public virtual DbSet<barang_terjual> barang_terjual { get; set; }
        public virtual DbSet<his_login> his_login { get; set; }
        public virtual DbSet<karyawan> karyawans { get; set; }
        public virtual DbSet<keranjang> keranjangs { get; set; }
        public virtual DbSet<notif> notifs { get; set; }
        public virtual DbSet<pelanggan> pelanggans { get; set; }
        public virtual DbSet<return_barang> return_barang { get; set; }
        public virtual DbSet<stok_toko> stok_toko { get; set; }
        public virtual DbSet<suplier> supliers { get; set; }
        public virtual DbSet<transaksi> transaksis { get; set; }
        public virtual DbSet<item> items { get; set; }
    }
}
