//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTeguhJaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int id { get; set; }
        public string NamaBarang { get; set; }
        public string JenisBarang { get; set; }
        public string SupplierBarang { get; set; }
        public Nullable<double> Modal { get; set; }
        public Nullable<double> HargaAtas { get; set; }
        public Nullable<double> HargaBawah { get; set; }
        public Nullable<int> JumlahDus { get; set; }
        public Nullable<int> SatuanKonversi { get; set; }
        public Nullable<int> Stok { get; set; }
        public Nullable<int> MinStock { get; set; }
        public Nullable<int> UmurBarangMaksimal { get; set; }
        public Nullable<int> UmurBarangNormal { get; set; }
        public Nullable<System.DateTime> TanggalMasuk { get; set; }
    }
}
