//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTeguhJaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class karyawan
    {
        public int id { get; set; }
        public string nama { get; set; }
        public string jekel { get; set; }
        public string jabatan { get; set; }
        public string alamat { get; set; }
        public string foto { get; set; }
        public string ktp { get; set; }
        public string nohp { get; set; }
        public int hutang { get; set; }
        public System.DateTime tgl_gaji { get; set; }
        public int jum_gaji { get; set; }
    }
}
