//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTeguhJaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class keranjang
    {
        public int id_keranjang { get; set; }
        public int id_barangtoko { get; set; }
        public int id_pelanggan { get; set; }
        public int jumlah_keranjang { get; set; }
        public int harga_akhir { get; set; }
        public string sub_total { get; set; }
        public string sub_totaldiskon { get; set; }
        public string total_hargadiskon { get; set; }
        public string id_sesion { get; set; }
        public System.DateTime tanggal { get; set; }
    }
}
