//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTeguhJaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class return_barang
    {
        public int id_return { get; set; }
        public int id_pelanggan { get; set; }
        public int id_barangtoko { get; set; }
        public int jumlah_barang { get; set; }
        public int harga { get; set; }
        public System.DateTime tanggal { get; set; }
        public string id_sesion { get; set; }
        public int harga_return { get; set; }
    }
}
