//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTeguhJaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok_toko
    {
        public int id_toko { get; set; }
        public int id_gudang { get; set; }
        public string nama_toko { get; set; }
        public string jenis_toko { get; set; }
        public string suplier_toko { get; set; }
        public int modal_toko { get; set; }
        public int harga_atas_toko { get; set; }
        public int harga_bawah_toko { get; set; }
        public int jumlah_toko { get; set; }
        public int sisa_toko { get; set; }
        public System.DateTime tanggal_masuktoko { get; set; }
    }
}
