//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTeguhJaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class suplier
    {
        public int id_suplier { get; set; }
        public string nama_suplier { get; set; }
        public string bank { get; set; }
        public int no_rekening { get; set; }
        public int hutang { get; set; }
        public System.DateTime tempo { get; set; }
    }
}
