//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTeguhJaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaksi
    {
        public int id_transaksi { get; set; }
        public int id_pelanggan { get; set; }
        public string tot_belanja { get; set; }
        public string jumlah_bayar { get; set; }
        public string kembalian { get; set; }
        public System.DateTime tgl_transaksi { get; set; }
        public string faktur { get; set; }
        public double hutang_pertgl { get; set; }
    }
}
